"""
    This is a setup.py script generated by py2applet
    
    Usage:
    python setup.py py2app
    """

from setuptools import setup

APP = ['NCDFViewer.py']
DATA_FILES = []
OPTIONS = dict(
               includes = [
                           # The backends are dynamically imported and thus we need to
                           # tell py2app about them.
                           'kiva.*',
                           'enable.*',
                           'enable.qt4.*',
                           'pyface.*',
                           'pyface.ui.qt4.*',
                           'pyface.ui.qt4.action.*',
                           'pyface.ui.qt4.timer.*',
                           'pyface.ui.qt4.wizard.*',
                           'pyface.ui.qt4.workbench.*',
                           'traitsui.qt4.*',
                           'traitsui.qt4.extra.*',
                           'PyQt4.pyqtconfig', 
                           'netCDF4_utils.*',
                           'netCDF4.*',
                           'netcdftime.*', 
                           'glob.*'],
               argv_emulation = True)

setup(
      app=APP,
      data_files=DATA_FILES,
      options={'py2app': OPTIONS},
      setup_requires=['py2app'],
      )
